### ISSUE TITLE
No support for different host between git ssh/gitlab

### ISSUE THREAD

**Issue by jatimix** [isamert/lab.el#5]
Hello, 

Thanks for the package, combined with alert and magit hook it's really cool.

However, there is an issue when the remote ssh git host is not the gitlab one.

Let's say your remote gitlab is `gitlab.company.com`, but when you SSH clone you point to ` git@git.company.com`.

Then lab.el will make request to 
`https://gitlab.company.com/api/v4/projects/https%3A%2F%2Fgit.company.com/project`
Which obviously fail.

It's an easy fix, as it's just adding a new variable, the api endpoint, + the SSH repo endpoint. Then chopping the url with both.
The second one can be defaulted as it's just here in case both host are different (usually only when using ssh clone).

The best would be make lab-host variable, a map, where we can defined multiple host/multiple ssh host, as the user might work on different gitlab host, which all have different ssh host. 

Maybe relying on .dir-locals.el to customize per project can be enough as a work-around, that's up to you.

**Comment by isamert** [comment]
I see, making lab.el compatible with multiple Gitlab hosts would require a little bit more effort and, as you pointed out `.dir-locals.el` might just work fine. But I see the value in it as you may call lab.el functions without necessarily being in a project and in that case `.dir-locals.el` have no utility here. As I am using only one GitLab instance, I'm not really interested in this feature but I'll happily accept a PR.

For the ssh host case, instead of introducing a new variable, I made a fix that doesn't require one if I understand your case correctly. Can you check out [this](https://github.com/isamert/lab.el/tree/fix-different-ssh-host) branch and see if it works for you?
